version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./flask_app:/usr/src/app/
    ports:
      - 5000:5000
    env_file: ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.prod.db
volumes:
  postgres_data: